import Link from 'next/link';
import { Card } from '@/components/ui';
import { getAttendanceHistory } from '@/lib/db/attendance-history';
import { HistoryActionForm } from './HistoryActionForm';

const STATUS:Record<string,string>={scheduled:'예정',working:'근무 중',checkout_pending:'승인 대기',completed:'완료',late:'지각',absent:'결근',leave:'휴가'};
const ENGAGEMENT:Record<string,string>={regular:'상시',fixed_term:'기간제',temporary:'임시',daily:'단기',shift:'공고 시프트'};
const AUTH:Record<string,string>={GPS:'위치',GPS_QR:'위치+QR',QR:'QR',QR_FALLBACK:'QR 보완',ADMIN:'관리자',qr:'기존 QR',button:'원터치'};
function moveMonth(month:string,delta:number){const d=new Date(`${month}-01T00:00:00Z`);d.setUTCMonth(d.getUTCMonth()+delta);return d.toISOString().slice(0,7);}
function dt(iso:string|null){if(!iso)return '—';return new Date(iso).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',hour12:false});}
function localInput(iso:string|null){if(!iso)return '';const d=new Date(new Date(iso).getTime()+9*3600000);return d.toISOString().slice(0,16);}

export default async function AttendanceHistoryPage({searchParams}:{searchParams:Promise<{month?:string;type?:string;status?:string}>}){
  const p=await searchParams;const current=new Date(Date.now()+9*3600000).toISOString().slice(0,7);
  // 목록은 최근 3개월까지만 — 그 이전 이력은 직원별 근태 페이지에서 조회
  const minMonth=moveMonth(current,-2);
  const requested=/^\d{4}-(0[1-9]|1[0-2])$/.test(p.month??'')?p.month!:current;
  const month=requested<minMonth?minMonth:requested>current?current:requested;
  const type=['all','staff','shift'].includes(p.type??'')?p.type!:'all';const status=['all','completed','issue','working'].includes(p.status??'')?p.status!:'all';
  const {rows,closed}=await getAttendanceHistory(month);
  const visible=rows.filter(r=>(type==='all'||r.kind===type)&&(status==='all'||(status==='issue'?['late','absent','checkout_pending'].includes(r.status)||r.lateMinutes>0||r.earlyLeaveMinutes>0:r.status===status)));
  const total=rows.reduce((s,r)=>s+r.workedMinutes,0),issues=rows.filter(r=>['late','absent','checkout_pending'].includes(r.status)||r.lateMinutes>0||r.earlyLeaveMinutes>0).length;
  return <main className="px-4 pb-28">
    <div className="mt-3 px-1"><p className="text-label font-bold text-primary">수정·감사 기록</p><h1 className="text-display font-extrabold">근태 내역</h1><p className="mt-1 text-label text-sub">확인이 필요한 날짜를 찾고 출퇴근 기록을 수정해요.</p></div>
    <div className="mt-4 flex gap-2"><Link href={`/attendance-summary?month=${month}`} className="flex h-10 flex-1 items-center justify-center rounded-xl border border-line bg-white text-[12px] font-bold">← 월 요약</Link><a href={`/api/attendance/export?month=${month}`} className="flex h-10 flex-1 items-center justify-center rounded-xl bg-ink text-[12px] font-bold text-white">CSV 내려받기</a></div>
    <div className="mt-4 flex items-center justify-between rounded-2xl bg-white p-2 shadow-sm">{month>minMonth?<Link href={`/attendance-history?month=${moveMonth(month,-1)}&type=${type}&status=${status}`} className="flex h-9 w-9 items-center justify-center text-xl">‹</Link>:<span className="flex h-9 w-9 items-center justify-center text-xl text-line">‹</span>}<b className="text-[14px]">{month.replace('-','년 ')}월</b>{month<current?<Link href={`/attendance-history?month=${moveMonth(month,1)}&type=${type}&status=${status}`} className="flex h-9 w-9 items-center justify-center text-xl">›</Link>:<span className="w-9 text-center text-line">›</span>}</div>
    {month<=minMonth&&<p className="mt-2 px-1 text-[11px] text-sub">더 오래된 기록은 아래 직원 이름을 눌러 직원별 근태에서 확인하세요.</p>}
    <div className="mt-3 grid grid-cols-3 gap-2"><Card className="p-3"><p className="text-[11px] text-sub">근태 기록</p><b className="mt-1 block text-title">{rows.length}건</b></Card><Card className="p-3"><p className="text-[11px] text-sub">총 인정 근무</p><b className="mt-1 block text-title">{Math.floor(total/60)}h</b></Card><Card className="p-3"><p className="text-[11px] text-sub">확인 필요</p><b className="mt-1 block text-title text-red-600">{issues}건</b></Card></div>
    <div className="mt-4 flex gap-2 overflow-x-auto pb-1" aria-label="근태 빠른 필터">
      {[['all','all','전체'],['staff','all','등록 직원'],['shift','all','단기 워커'],['all','issue',`확인 필요 ${issues}`],['all','completed','완료']].map(([nextType,nextStatus,label])=><Link key={`${nextType}-${nextStatus}`} href={`/attendance-history?month=${month}&type=${nextType}&status=${nextStatus}`} className={`shrink-0 rounded-full px-3 py-2 text-[12px] font-bold ${(type===nextType&&status===nextStatus)?'bg-ink text-white':'border border-line bg-white text-sub'}`}>{label}</Link>)}
    </div>
    <Card className={`mt-4 border ${closed?'border-emerald-200 bg-emerald-50':'border-amber-200 bg-amber-50'}`}>
      <div className="flex items-start justify-between gap-3"><div><p className="text-[13px] font-extrabold">{closed?'이 월의 근태를 마감했어요':month===current?'이번 달 근태를 집계하고 있어요':'아직 마감하지 않은 근태예요'}</p><p className="mt-1 text-[12px] text-sub">{closed?'수정하려면 사유를 입력하고 재개방하세요.':month===current?'월이 끝난 다음 달부터 마감할 수 있어요.':'기록 확인 후 마감하면 급여 검토 기준이 고정돼요.'}</p></div><span className="shrink-0 rounded-full bg-white px-2 py-1 text-[11px] font-bold">{closed?'마감':'진행 중'}</span></div>
      {(closed||month<current)&&<HistoryActionForm kind="period" className="mt-3"><input type="hidden" name="month" value={month}/><input type="hidden" name="action" value={closed?'reopen':'close'}/><input name="reason" required minLength={5} placeholder={closed?'재개방 사유를 입력하세요':'월 근태 확인 완료'} className="h-10 w-full rounded-xl border border-line bg-white px-3 text-[12px]"/><button className={`mt-2 h-10 w-full rounded-xl text-[12px] font-bold text-white ${closed?'bg-amber-600':'bg-success'}`}>{closed?'사유 입력 후 재개방':'이 월 근태 마감'}</button></HistoryActionForm>}
    </Card>
    <div className="mt-5 space-y-3">{visible.length===0?<Card className="py-9 text-center font-bold">조건에 맞는 근태 기록이 없어요.</Card>:visible.map(row=><Card key={`${row.kind}-${row.id}`} className="p-4">
      <div className="flex justify-between gap-3"><div><div className="flex items-center gap-2">{row.staffId?<Link href={`/attendance-history/staff/${row.staffId}?month=${month}`} className="font-bold text-primary underline-offset-2 hover:underline">{row.name}</Link>:<b>{row.name}</b>}<span className="rounded bg-bg px-1.5 py-0.5 text-[10px] font-bold text-sub">{ENGAGEMENT[row.employment]??row.employment}</span></div><p className="mt-1 text-[12px] text-sub">{row.workDate} · 예정 {row.scheduledStart?.slice(0,5)??'—'}~{row.scheduledEnd?.slice(0,5)??'—'}</p></div><span className="h-fit rounded-full bg-bg px-2.5 py-1 text-[11px] font-bold">{STATUS[row.status]??row.status}</span></div>
      <div className="mt-3 rounded-xl bg-bg p-3 text-[12px]"><div className="flex justify-between"><span className="text-sub">실제 출퇴근</span><b>{dt(row.checkInAt)} → {dt(row.checkOutAt)}</b></div><div className="mt-2 flex justify-between"><span className="text-sub">인정 근무</span><b>{Math.floor(row.workedMinutes/60)}시간 {row.workedMinutes%60}분</b></div><div className="mt-2 flex justify-between"><span className="text-sub">인증</span><b>{AUTH[row.method??'']??row.method??'—'}</b></div>{(row.lateMinutes>0||row.earlyLeaveMinutes>0)&&<p className="mt-2 text-right font-bold text-warn">{row.lateMinutes>0?`지각 ${row.lateMinutes}분`:''}{row.earlyLeaveMinutes>0?` · 조퇴 ${row.earlyLeaveMinutes}분`:''}</p>}</div>
      {row.kind==='staff'&&!closed&&row.checkInAt&&row.checkOutAt&&<details className="mt-3"><summary className="cursor-pointer text-right text-[12px] font-bold text-primary">기록 수정</summary><HistoryActionForm kind="correct" className="mt-3 rounded-xl border border-line p-3"><input type="hidden" name="attendance_id" value={row.id}/><input type="hidden" name="month" value={month}/><div className="grid grid-cols-2 gap-2"><label className="text-[11px] text-sub">출근<input type="datetime-local" name="check_in" required defaultValue={localInput(row.checkInAt)} className="mt-1 h-10 w-full rounded-lg border border-line px-2"/></label><label className="text-[11px] text-sub">퇴근<input type="datetime-local" name="check_out" required defaultValue={localInput(row.checkOutAt)} className="mt-1 h-10 w-full rounded-lg border border-line px-2"/></label><label className="col-span-2 text-[11px] text-sub">휴게시간(분)<input type="number" name="break_minutes" min="0" max="480" required defaultValue={row.breakMinutes} className="mt-1 h-10 w-full rounded-lg border border-line px-3"/></label><label className="col-span-2 text-[11px] text-sub">수정 사유<input name="reason" required minLength={5} placeholder="예: 직원 요청으로 누락 퇴근시간 보완" className="mt-1 h-10 w-full rounded-lg border border-line px-3"/></label></div><button className="mt-3 h-10 w-full rounded-xl bg-primary text-[12px] font-bold text-white">사유와 함께 수정</button></HistoryActionForm></details>}
      {row.kind==='shift'&&<p className="mt-3 text-[11px] text-sub">공고 시프트 시간 수정은 급여 금액과 연결되므로 지급관리에서 함께 검토해 주세요.</p>}
    </Card>)}</div>
    <Link href={`/payroll?month=${month}`} className="mt-5 flex h-12 items-center justify-center rounded-xl bg-primary font-bold text-white">이 월 급여 검토하기 →</Link>
  </main>;
}
